[tool.poetry]
name = "projects"
version = "0.1.0"
description = ""
authors = ["nick"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
acryl-datahub = "^0.12.1.3"
dbt = "^1.0.0.35.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
